; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+sve -verify-machineinstrs \
; RUN:   -enable-legalize-types-checking %s -o - | FileCheck %s


define <vscale x 3 x i64> @interleave3_nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c) #0 {
; CHECK-LABEL: interleave3_nxv1i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-10
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0a, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x11, 0xd0, 0x00, 0x1e, 0x22 // sp + 16 + 80 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    // kill: def $z2 killed $z2 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    rdvl x8, #1
; CHECK-NEXT:    mov w9, #3 // =0x3
; CHECK-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    cnth x10
; CHECK-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    st3d { z0.d - z2.d }, p0, [sp]
; CHECK-NEXT:    ldr z0, [sp, #2, mul vl]
; CHECK-NEXT:    ldr z1, [sp]
; CHECK-NEXT:    mul x9, x8, x9
; CHECK-NEXT:    whilelo p0.d, xzr, x8
; CHECK-NEXT:    addvl x8, sp, #4
; CHECK-NEXT:    add x8, x8, x10
; CHECK-NEXT:    whilelo p1.s, xzr, x9
; CHECK-NEXT:    str z0, [sp, #6, mul vl]
; CHECK-NEXT:    ldr z0, [sp, #1, mul vl]
; CHECK-NEXT:    str z1, [sp, #4, mul vl]
; CHECK-NEXT:    str z1, [sp, #3, mul vl]
; CHECK-NEXT:    str z0, [sp, #5, mul vl]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x8]
; CHECK-NEXT:    addvl x8, sp, #3
; CHECK-NEXT:    add x8, x8, x10
; CHECK-NEXT:    st1d { z1.d }, p0, [x8]
; CHECK-NEXT:    punpkhi p0.h, p1.b
; CHECK-NEXT:    addvl x8, sp, #2
; CHECK-NEXT:    ldr z1, [sp, #3, mul vl]
; CHECK-NEXT:    punpklo p1.h, p1.b
; CHECK-NEXT:    st1d { z0.d }, p0, [x8, #7, mul vl]
; CHECK-NEXT:    addvl x8, sp, #1
; CHECK-NEXT:    st1d { z1.d }, p1, [x8, #7, mul vl]
; CHECK-NEXT:    ldr z0, [sp, #8, mul vl]
; CHECK-NEXT:    ldr z1, [sp, #9, mul vl]
; CHECK-NEXT:    addvl sp, sp, #10
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %r = call <vscale x 3 x i64> @llvm.vector.interleave3.nxv3i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c)
  ret <vscale x 3 x i64> %r
}

define { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64> } @deinterleave3_nxv1i64(<vscale x 3 x i64> %a) #0 {
; CHECK-LABEL: deinterleave3_nxv1i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-9
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0a, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x11, 0xc8, 0x00, 0x1e, 0x22 // sp + 16 + 72 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    rdvl x8, #1
; CHECK-NEXT:    cnth x9
; CHECK-NEXT:    str z1, [sp, #8, mul vl]
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    str z0, [sp, #7, mul vl]
; CHECK-NEXT:    ptrue p1.b
; CHECK-NEXT:    str z0, [sp, #3, mul vl]
; CHECK-NEXT:    whilelo p0.d, xzr, x8
; CHECK-NEXT:    addvl x8, sp, #7
; CHECK-NEXT:    add x8, x8, x9
; CHECK-NEXT:    ld1d { z2.d }, p0/z, [x8]
; CHECK-NEXT:    addvl x8, sp, #3
; CHECK-NEXT:    st1b { z2.b }, p1, [x8, x9]
; CHECK-NEXT:    str z1, [sp, #6, mul vl]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [sp, #6, mul vl]
; CHECK-NEXT:    str z0, [sp, #5, mul vl]
; CHECK-NEXT:    ldr z0, [sp, #3, mul vl]
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    str z1, [sp, #1, mul vl]
; CHECK-NEXT:    str z0, [sp]
; CHECK-NEXT:    ld3d { z0.d - z2.d }, p0/z, [sp]
; CHECK-NEXT:    addvl sp, sp, #9
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %r = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64> } @llvm.vector.deinterleave3.nxv3i64(<vscale x 3 x i64> %a)
  ret { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64> } %r
}

attributes #0 = { "target-features"="+sve" }
