; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s | FileCheck --check-prefix=AS %s

target datalayout = "e-m:e-i64:64-i128:128-n32:64-S128"
target triple = "arm64--linux-gnu"

define void @aarch64_vector_deinterleave_idx_ld2(ptr %ptr, i64 %idx) {
; AS-LABEL: aarch64_vector_deinterleave_idx_ld2:
; AS:       // %bb.0: // %entry
; AS-NEXT:    lsl x8, x1, #2
; AS-NEXT:    and x9, x8, #0xfffffffffffffff0
; AS-NEXT:    add x8, x8, #16
; AS-NEXT:    add x10, x0, x9
; AS-NEXT:    and x8, x8, #0xfffffffffffffff0
; AS-NEXT:    ld2 { v0.4s, v1.4s }, [x10]
; AS-NEXT:    str q0, [x0, x9]
; AS-NEXT:    str q1, [x0, x8]
; AS-NEXT:    ret
entry:
  %idx1 = lshr i64 %idx, 2
  %a1 = add i64 %idx, 4
  %idx2 = lshr i64 %a1, 2

  %gep1 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx1
  %gep2 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx2

  %load = load <8 x float>, ptr %gep1, align 16
  %deinterleave = call { <4 x float>, <4 x float> } @llvm.vector.deinterleave2.v8f32(<8 x float> %load)
  %m0_3 = extractvalue { <4 x float>, <4 x float> } %deinterleave, 0
  %m4_7 = extractvalue { <4 x float>, <4 x float> } %deinterleave, 1

  store <4 x float> %m0_3, ptr %gep1, align 16
  store <4 x float> %m4_7, ptr %gep2, align 16
  ret void
}

define void @aarch64_vector_deinterleave_idx_ld3(ptr %ptr, i64 %idx) {
; AS-LABEL: aarch64_vector_deinterleave_idx_ld3:
; AS:       // %bb.0: // %entry
; AS-NEXT:    lsl x8, x1, #2
; AS-NEXT:    and x9, x8, #0xfffffffffffffff0
; AS-NEXT:    add x10, x0, x9
; AS-NEXT:    ld3 { v0.4s, v1.4s, v2.4s }, [x10]
; AS-NEXT:    add x10, x8, #16
; AS-NEXT:    add x8, x8, #32
; AS-NEXT:    and x10, x10, #0xfffffffffffffff0
; AS-NEXT:    and x8, x8, #0xfffffffffffffff0
; AS-NEXT:    str q0, [x0, x9]
; AS-NEXT:    str q1, [x0, x10]
; AS-NEXT:    str q2, [x0, x8]
; AS-NEXT:    ret
entry:
  %idx1 = lshr i64 %idx, 2
  %a1 = add i64 %idx, 4
  %idx2 = lshr i64 %a1, 2
  %a2 = add i64 %idx, 8
  %idx3 = lshr i64 %a2, 2

  %gep1 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx1
  %gep2 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx2
  %gep3 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx3

  %load = load <12 x float>, ptr %gep1, align 16
  %deinterleave = call { <4 x float>, <4 x float>, <4 x float> } @llvm.vector.deinterleave3.v12f32(<12 x float> %load)
  %m0_3 = extractvalue { <4 x float>, <4 x float>, <4 x float> } %deinterleave, 0
  %m4_7 = extractvalue { <4 x float>, <4 x float>, <4 x float> } %deinterleave, 1
  %m8_11 = extractvalue { <4 x float>, <4 x float>, <4 x float> } %deinterleave, 2

  store <4 x float> %m0_3, ptr %gep1, align 16
  store <4 x float> %m4_7, ptr %gep2, align 16
  store <4 x float> %m8_11, ptr %gep3, align 16
  ret void
}

define void @aarch64_vector_deinterleave_idx_ld4(ptr %ptr, i64 %idx) {
; AS-LABEL: aarch64_vector_deinterleave_idx_ld4:
; AS:       // %bb.0: // %entry
; AS-NEXT:    lsl x8, x1, #2
; AS-NEXT:    add x9, x8, #64
; AS-NEXT:    add x11, x8, #96
; AS-NEXT:    and x9, x9, #0xfffffffffffffff0
; AS-NEXT:    add x10, x0, x9
; AS-NEXT:    ld4 { v0.4s, v1.4s, v2.4s, v3.4s }, [x10]
; AS-NEXT:    add x10, x8, #80
; AS-NEXT:    add x8, x8, #112
; AS-NEXT:    and x10, x10, #0xfffffffffffffff0
; AS-NEXT:    and x8, x8, #0xfffffffffffffff0
; AS-NEXT:    str q0, [x0, x9]
; AS-NEXT:    and x9, x11, #0xfffffffffffffff0
; AS-NEXT:    str q1, [x0, x10]
; AS-NEXT:    str q2, [x0, x9]
; AS-NEXT:    str q3, [x0, x8]
; AS-NEXT:    ret
entry:
  %a1 = add i64 %idx, 16
  %idx1 = lshr i64 %a1, 2
  %a2 = add i64 %idx, 20
  %idx2 = lshr i64 %a2, 2
  %a3 = add i64 %idx, 24
  %idx3 = lshr i64 %a3, 2
  %a4 = add i64 %idx, 28
  %idx4 = lshr i64 %a4, 2

  %gep1 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx1
  %gep2 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx2
  %gep3 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx3
  %gep4 = getelementptr inbounds <4 x float>, ptr %ptr, i64 %idx4

  %load = load <16 x float>, ptr %gep1, align 16
  %deinterleave = call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.vector.deinterleave4.v16f32(<16 x float> %load)
  %m0_3 = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %deinterleave, 0
  %m4_7 = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %deinterleave, 1
  %m8_11 = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %deinterleave, 2
  %m12_15 = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %deinterleave, 3

  store <4 x float> %m0_3, ptr %gep1, align 16
  store <4 x float> %m4_7, ptr %gep2, align 16
  store <4 x float> %m8_11, ptr %gep3, align 16
  store <4 x float> %m12_15, ptr %gep4, align 16
  ret void
}


define void @aarch64_vector_deinterleave_fixed_sve_ld2(ptr %src, ptr %dst0, ptr %dst1) #0 {
; AS-LABEL: aarch64_vector_deinterleave_fixed_sve_ld2:
; AS:       // %bb.0:
; AS-NEXT:    ldr z0, [x0, #1, mul vl]
; AS-NEXT:    ldr z1, [x0]
; AS-NEXT:    uzp1 z2.d, z1.d, z0.d
; AS-NEXT:    uzp2 z0.d, z1.d, z0.d
; AS-NEXT:    str z2, [x1]
; AS-NEXT:    str z0, [x2]
; AS-NEXT:    ret
  %load = load <8 x double>, ptr %src, align 16
  %deinterleave = call { <4 x double>, <4 x double> } @llvm.vector.deinterleave2.v8f64(<8 x double> %load)
  %even = extractvalue { <4 x double>, <4 x double> } %deinterleave, 0
  %odd = extractvalue { <4 x double>, <4 x double> } %deinterleave, 1
  store <4 x double> %even, ptr %dst0, align 16
  store <4 x double> %odd, ptr %dst1, align 16
  ret void
}


attributes #0 = { "target-features"="+sve" vscale_range(2,2) }
