; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+sve %s -o - | FileCheck %s

define <9 x i16> @interleave3_v9i16(<3 x i16> %vec0, <3 x i16> %vec1, <3 x i16> %vec2) {
; CHECK-LABEL: interleave3_v9i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmov d3, d2
; CHECK-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-NEXT:    adrp x9, .LCPI0_0
; CHECK-NEXT:    fmov d2, d0
; CHECK-NEXT:    ldr q0, [x9, :lo12:.LCPI0_0]
; CHECK-NEXT:    mov v2.d[1], v1.d[0]
; CHECK-NEXT:    mov h1, v3.h[2]
; CHECK-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-NEXT:    str h1, [x8, #16]
; CHECK-NEXT:    str q0, [x8]
; CHECK-NEXT:    ret
  %retval = call <9 x i16> @llvm.vector.interleave3.v9i16(<3 x i16> %vec0, <3 x i16> %vec1, <3 x i16> %vec2)
  ret <9 x i16> %retval
}

define <vscale x 9 x i16> @interleave3_nxv9i16(<vscale x 3 x i16> %vec0, <vscale x 3 x i16> %vec1, <vscale x 3 x i16> %vec2) #0 {
; CHECK-LABEL: interleave3_nxv9i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-12
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0a, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x11, 0xe0, 0x00, 0x1e, 0x22 // sp + 16 + 96 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    // kill: def $z2 killed $z2 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    rdvl x8, #1
; CHECK-NEXT:    mov w9, #3 // =0x3
; CHECK-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    addvl x10, sp, #6
; CHECK-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1_z2 def $z0_z1_z2
; CHECK-NEXT:    st3w { z0.s - z2.s }, p0, [sp]
; CHECK-NEXT:    ldr z0, [sp, #2, mul vl]
; CHECK-NEXT:    ldr z1, [sp, #1, mul vl]
; CHECK-NEXT:    ldr z2, [sp]
; CHECK-NEXT:    mul x9, x8, x9
; CHECK-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-NEXT:    uzp1 z1.h, z2.h, z1.h
; CHECK-NEXT:    uzp1 z2.h, z2.h, z0.h
; CHECK-NEXT:    whilelo p0.s, xzr, x9
; CHECK-NEXT:    cntd x9, all, mul #3
; CHECK-NEXT:    add x10, x10, x9
; CHECK-NEXT:    str z0, [sp, #7, mul vl]
; CHECK-NEXT:    str z1, [sp, #6, mul vl]
; CHECK-NEXT:    str z2, [sp, #3, mul vl]
; CHECK-NEXT:    ld1h { z2.s }, p0/z, [x10]
; CHECK-NEXT:    addvl x10, sp, #3
; CHECK-NEXT:    add x9, x10, x9
; CHECK-NEXT:    cntw x10, all, mul #3
; CHECK-NEXT:    st1h { z2.s }, p0, [x9]
; CHECK-NEXT:    mov w9, #9 // =0x9
; CHECK-NEXT:    str z0, [sp, #5, mul vl]
; CHECK-NEXT:    ldr z0, [sp, #3, mul vl]
; CHECK-NEXT:    mul x8, x8, x9
; CHECK-NEXT:    addvl x9, sp, #4
; CHECK-NEXT:    str z1, [sp, #4, mul vl]
; CHECK-NEXT:    add x9, x9, x10
; CHECK-NEXT:    str z0, [sp, #8, mul vl]
; CHECK-NEXT:    ld1h { z0.s }, p0/z, [x9]
; CHECK-NEXT:    addvl x9, sp, #8
; CHECK-NEXT:    add x9, x9, x10
; CHECK-NEXT:    whilelo p1.b, xzr, x8
; CHECK-NEXT:    addvl x8, sp, #4
; CHECK-NEXT:    st1h { z0.s }, p0, [x9]
; CHECK-NEXT:    punpkhi p0.h, p1.b
; CHECK-NEXT:    ldr z0, [sp, #9, mul vl]
; CHECK-NEXT:    ldr z1, [sp, #8, mul vl]
; CHECK-NEXT:    punpklo p1.h, p1.b
; CHECK-NEXT:    st1h { z0.h }, p0, [x8, #7, mul vl]
; CHECK-NEXT:    addvl x8, sp, #3
; CHECK-NEXT:    st1h { z1.h }, p1, [x8, #7, mul vl]
; CHECK-NEXT:    ldr z0, [sp, #10, mul vl]
; CHECK-NEXT:    ldr z1, [sp, #11, mul vl]
; CHECK-NEXT:    addvl sp, sp, #12
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %retval = call <vscale x 9 x i16> @llvm.vector.interleave3.nxv9i16(<vscale x 3 x i16> %vec0, <vscale x 3 x i16> %vec1, <vscale x 3 x i16> %vec2)
  ret <vscale x 9 x i16> %retval
}

attributes #0 = { vscale_range(1,16) }
