; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs \
; RUN:   -enable-legalize-types-checking %s  -o - | FileCheck %s

declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.vector.deinterleave3.v3i64(<3 x i64>)

define <3 x i64> @interleave3_v1i64(<1 x i64> %a, <1 x i64> %b, <1 x i64> %c) {
; CHECK-LABEL: interleave3_v1i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    movq %rsi, %rdx
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    retq
  %r = call <3 x i64> @llvm.vector.interleave3.v3i64(<1 x i64> %a, <1 x i64> %b, <1 x i64> %c)
  ret <3 x i64> %r
}

define { <1 x i64>, <1 x i64>, <1 x i64> } @deinterleave3_v1i64(<3 x i64> %a) {
; CHECK-LABEL: deinterleave3_v1i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    movq %rsi, %rdx
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    retq
  %r = call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.vector.deinterleave3.v3i64(<3 x i64> %a)
  ret { <1 x i64>, <1 x i64>, <1 x i64> } %r
}
