; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s

declare <4 x i32> @llvm.vector.interleave2.v4i32(<2 x i32>, <2 x i32>)
declare { <2 x i32>, <2 x i32> } @llvm.vector.deinterleave2.v4i32(<4 x i32>)

define <4 x i32> @interleave(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: interleave:
; CHECK:       # %bb.0:
; CHECK-NEXT:    unpcklps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[1],xmm1[1]
; CHECK-NEXT:    retq
  %r = call <4 x i32> @llvm.vector.interleave2.v4i32(<2 x i32> %a, <2 x i32> %b)
  ret <4 x i32> %r
}

define { <2 x i32>, <2 x i32> } @deinterleave(<4 x i32> %a) {
; CHECK-LABEL: deinterleave:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm0[0,2,2,3]
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[1,3,2,3]
; CHECK-NEXT:    movdqa %xmm2, %xmm0
; CHECK-NEXT:    retq
  %r = call { <2 x i32>, <2 x i32> } @llvm.vector.deinterleave2.v4i32(<4 x i32> %a)
  ret { <2 x i32>, <2 x i32> } %r
}
